# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CIGNN-experimental',
                'doc_host': 'https://TimHal.github.io',
                'git_url': 'https://github.com/TimHal/CIGNN-experimental',
                'lib_path': 'CIGNN_experimental'},
  'syms': {'CIGNN_experimental.core': {'CIGNN_experimental.core.foo': ('core.html#foo', 'CIGNN_experimental/core.py')}}}
