# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/CIGNN-experimental',
                'doc_host': 'https://TimHal.github.io',
                'git_url': 'https://github.com/TimHal/CIGNN-experimental',
                'lib_path': 'CIGNN_experimental'},
  'syms': { 'CIGNN_experimental.core': {'CIGNN_experimental.core.foo': ('core.html#foo', 'CIGNN_experimental/core.py')},
            'CIGNN_experimental.data': { 'CIGNN_experimental.data.SaintGallDataset': ( 'cignn_01_transforms.html#saintgalldataset',
                                                                                       'CIGNN_experimental/data.py'),
                                         'CIGNN_experimental.data.SaintGallDataset.__getitem__': ( 'cignn_01_transforms.html#saintgalldataset.__getitem__',
                                                                                                   'CIGNN_experimental/data.py'),
                                         'CIGNN_experimental.data.SaintGallDataset.__init__': ( 'cignn_01_transforms.html#saintgalldataset.__init__',
                                                                                                'CIGNN_experimental/data.py'),
                                         'CIGNN_experimental.data.SaintGallDataset.__len__': ( 'cignn_01_transforms.html#saintgalldataset.__len__',
                                                                                               'CIGNN_experimental/data.py')},
            'CIGNN_experimental.experiments': { 'CIGNN_experimental.experiments.say_hello': ( 'experiments.html#say_hello',
                                                                                              'CIGNN_experimental/experiments.py')},
            'CIGNN_experimental.models.cnn.LeNet': {}}}
