"""Detecting (and inverting?) transformations on HW samples"""

# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/21_CIGNN_01_Transforms.ipynb.

# %% auto 0
__all__ = ['SaintGallDataset']

# %% ../nbs/21_CIGNN_01_Transforms.ipynb 7
class SaintGallDataset(Dataset):
    """Dataset class for accessing the local Saint Gall Dataset as text lines.

    The samples from this class are the (annotated) normalised line images in binarised form.
    """
    def __init__(self, split_file_path, dataset_root_path="/data/datasets/saintgalldb-v1.0/saintgalldb-v1.0", transform=None, target_transform=None):
        """Set up the dataset class and calculate the number of text lines for the current split.

        The `split_file` parameter is expected to point to either train.txt, test.txt, valid.txt or a custom split file
        of the same format containing a single fullpage-id per line. The line contents and images can then be 
        inferred by relative paths from the dataset root directory.
        """

        self.dataset_root_path = dataset_root_path
        # contains one fullpage img id per entry
        self.split = pd.read_csv(split_file_path)
        
        with open(os.path.join(self.dataset_root_path, "ground_truth", "transcription.txt"), "r") as fh:
            self._transcription = fh.readlines()

        # Now we can filter the transcription to only contain the lines belonging to the current split
        self.transcription = pd.DataFrame([line.split(" ") for line in self._transcription if line.startswith(tuple(self.split))])
        self.img_dir_path = os.path.join(self.dataset_root_path, "data", "line_images_normalized")

        self.transform = transform
        self.target_transform = target_transform
        

    def __len__(self):
        return len(self.transcription)

    def __getitem__(self, idx):
        img_path = os.path.join(self.img_dir_path, self.transcription.iloc[idx, 0] + '.png') 
        _image = read_image(img_path)

        # Since the images have different widths we naively pad them to a safe upper bound of 2000 for now
        
        image = TF.resize(_image, size=(120, 1024))


        label = self.transcription.iloc[idx, 1]
        label = label.replace("-", "").replace("|", " ")
        if self.transform:
            image = self.transform(image)
        if self.target_transform:
            label = self.target_transform(label)
        return image, label
